name: Update Comments

on:
  discussion_comment:
    types: [created, edited, deleted]

  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  #group: "pages"
  #cancel-in-progress: false
  group: "comment-sync"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    if: ${{ github.event.comment.user.type != 'Bot' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      - name: _site rw Permission
        run: |
          sudo chown -R $USER:$USER ./_site
          sudo chmod -R 777 ${{ github.workspace }}/_site

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Inject Comments
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          node resources/js/backend/inject.js

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
